updated template to match changes in release

diff --git a/templates/cluster-launch-installer-e2e-modified.yaml b/templates/cluster-launch-installer-e2e-modified.yaml
--- a/templates/cluster-launch-installer-e2e-modified.yaml
+++ b/templates/cluster-launch-installer-e2e-modified.yaml
@@ -11,22 +11,18 @@ parameters:
   value: "your-ns"
 - name: IMAGE_FORMAT
   required: true
-- name: LOCAL_IMAGE_INSTALLER
+- name: IMAGE_INSTALLER
   required: true
 - name: IMAGE_TESTS
   required: true
 - name: CLUSTER_TYPE
   # MODIFIED
   value: "aws"
-- name: TEST_FOCUS
-- name: TEST_SKIP
-- name: TEST_FOCUS_SERIAL
-- name: TEST_SKIP_SERIAL
-- name: TEST_PARALLELISM
-  value: "30"
 # Ensures the release image is created and tested
 - name: TEST_COMMAND
+  required: true
 - name: RELEASE_IMAGE_LATEST
+  required: true
 
 objects:
 
@@ -83,8 +79,8 @@ objects:
       - name: shared-tmp
         mountPath: /tmp/shared
       #MODIFIED
-      #- name: cluster-profile
-      #  mountPath: /tmp/cluster
+      - name: cluster-profile
+        mountPath: /tmp/cluster
       - name: artifacts
         mountPath: /tmp/artifacts
       env:
@@ -99,8 +95,12 @@ objects:
         #!/bin/bash
         set -euo pipefail
 
+        export PATH=/usr/libexec/origin:$PATH
+
         trap 'touch /tmp/shared/exit' EXIT
         trap 'kill $(jobs -p); exit 0' TERM
+
+        cp "$(which oc)" /tmp/shared/
 
         mkdir -p "${HOME}"
 
@@ -150,11 +150,14 @@ objects:
           break
         done
 
-        if ! oc wait deploy/router -n "${ROUTER_NAMESPACE}" --for condition=available --timeout=20m; then
-          echo "Installation failed"
-          cp $KUBECONFIG /tmp/admin.kubeconfig
-          exit 1
-        fi
+        i=0
+        MAX_RETRIES=10
+        until oc wait deploy/router -n "${ROUTER_NAMESPACE}" --for condition=available --timeout=10m || [ $i -eq $MAX_RETRIES ]; do
+            i=$((i+1))
+            [ $i -eq $MAX_RETRIES ] && echo "timeout waiting for router to be available" && exit 1
+            echo "error deploy/router did not come up"
+            sleep 60
+        done
 
         # set up cloud-provider-specific env vars
         if [[ "${CLUSTER_TYPE}" == "gcp" ]]; then
@@ -184,25 +187,27 @@ objects:
         # TODO: the test binary should really be a more structured command - most of these flags should be
         #       autodetected from the running cluster.
         # TODO: bump nodes up to 40 again
-        PATH="/usr/libexec/origin:${PATH}"
-        set -x
-        if [[ -n "${TEST_FOCUS}" ]]; then
-          ginkgo -v -noColor -nodes=${TEST_PARALLELISM} $( which extended.test ) -- \
-            -ginkgo.focus="${TEST_FOCUS}" -ginkgo.skip="${TEST_SKIP}" \
-            -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit \
-            -test.timeout=10m ${PROVIDER_ARGS-} || rc=$?
-        fi
-        if [[ -n "${TEST_FOCUS_SERIAL}" ]]; then
-          ginkgo -v -noColor -nodes=1 $( which extended.test ) -- \
-            -ginkgo.focus="${TEST_FOCUS_SERIAL}" -ginkgo.skip="${TEST_SKIP_SERIAL}" \
-            -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit/serial \
-            -test.timeout=20m ${PROVIDER_ARGS-} || rc=$?
-        fi
-        exit ${rc:-0}
+        function run-tests() {
+          if [[ -n "${TEST_FOCUS:-}" ]]; then
+            ginkgo -v -noColor -nodes="${TEST_PARALLELISM:-30}" $( which extended.test ) -- \
+              -ginkgo.focus="${TEST_FOCUS}" -ginkgo.skip="${TEST_SKIP:-"\\[local\\]"}" \
+              -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit \
+              -test.timeout=2h ${PROVIDER_ARGS-} || rc=$?
+          fi
+          if [[ -n "${TEST_FOCUS_SERIAL:-}" ]]; then
+            ginkgo -v -noColor -nodes=1 $( which extended.test ) -- \
+              -ginkgo.focus="${TEST_FOCUS_SERIAL}" -ginkgo.skip="${TEST_SKIP_SERIAL:-"\\[local\\]"}" \
+              -e2e-output-dir /tmp/artifacts -report-dir /tmp/artifacts/junit/serial \
+              -test.timeout=2h ${PROVIDER_ARGS-} || rc=$?
+          fi
+          exit ${rc:-0}
+        }
+
+        ${TEST_COMMAND}
 
     # Runs an install
     - name: setup
-      image: ${LOCAL_IMAGE_INSTALLER}
+      image: ${IMAGE_INSTALLER}
       volumeMounts:
       - name: shared-tmp
         mountPath: /tmp
@@ -234,28 +239,27 @@ objects:
         value: aws
       - name: OPENSHIFT_INSTALL_AWS_REGION
         value: us-east-1
+      - name: OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE
+        value: ${RELEASE_IMAGE_LATEST}
       command:
-      - /bin/openshift-install
-      - --dir=/tmp/artifacts/installer
-      - --log-level=debug
-      - cluster
+      - /bin/sh
+      - -c
+      - |
+        #!/bin/sh
+        export _CI_ONLY_STAY_AWAY_OPENSHIFT_INSTALL_AWS_USER_TAGS="{\"expirationDate\": \"$(date -d '4 hours' --iso=minutes --utc)\"}"
+        exec /bin/openshift-install --dir=/tmp/artifacts/installer --log-level=debug cluster
 
     # Performs cleanup of all created resources
     - name: teardown
-      image: ${LOCAL_IMAGE_INSTALLER}
+      image: ${IMAGE_INSTALLER}
       volumeMounts:
       - name: shared-tmp
         mountPath: /tmp/shared
-        # MODIFIED
       - name: cluster-profile
         mountPath: /etc/openshift-installer
       - name: artifacts
         mountPath: /tmp/artifacts
       env:
-      - name: AWS_SHARED_CREDENTIALS_FILE
-        # MODIFIED
-        #value: /etc/openshift-installer/.awscred
-        value: /etc/openshift-installer/credentials
       - name: INSTANCE_PREFIX
         value: ${NAMESPACE}-${JOB_NAME_HASH}
       - name: TYPE
@@ -267,6 +271,22 @@ objects:
       - -c
       - |
         #!/bin/bash
+        function queue() {
+          local TARGET="${1}"
+          shift
+          local LIVE="$(jobs | wc -l)"
+          while [[ "${LIVE}" -ge 10 ]]; do
+            sleep 1
+            LIVE="$(jobs | wc -l)"
+          done
+          echo "${@}"
+          if [[ -n "${FILTER}" ]]; then
+            "${@}" | "${FILTER}" >"${TARGET}" &
+          else
+            "${@}" >"${TARGET}" &
+          fi
+        }
+
         function teardown() {
           set +e
           touch /tmp/shared/exit
@@ -277,45 +297,45 @@ objects:
 
           oc --request-timeout=5s get nodes -o jsonpath --template '{range .items[*]}{.metadata.name}{"\n"}{end}' > /tmp/nodes
           oc --request-timeout=5s get pods --all-namespaces --template '{{ range .items }}{{ $name := .metadata.name }}{{ $ns := .metadata.namespace }}{{ range .spec.containers }}-n {{ $ns }} {{ $name }} -c {{ .name }}{{ "\n" }}{{ end }}{{ range .spec.initContainers }}-n {{ $ns }} {{ $name }} -c {{ .name }}{{ "\n" }}{{ end }}{{ end }}' > /tmp/containers
-          oc --request-timeout=5s get nodes -o json > /tmp/artifacts/nodes.json
-          oc --request-timeout=5s get events --all-namespaces -o json > /tmp/artifacts/events.json
           oc --request-timeout=5s get pods -l openshift.io/component=api --all-namespaces --template '{{ range .items }}-n {{ .metadata.namespace }} {{ .metadata.name }}{{ "\n" }}{{ end }}' > /tmp/pods-api
+
+          queue /tmp/artifacts/nodes.json oc --request-timeout=5s get nodes -o json
+          queue /tmp/artifacts/events.json oc --request-timeout=5s get events --all-namespaces -o json
 
           # gather nodes first in parallel since they may contain the most relevant debugging info
           while IFS= read -r i; do
             mkdir -p /tmp/artifacts/nodes/$i
-            (
-            oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/messages | gzip -c > /tmp/artifacts/nodes/$i/messages.gz
+            FILTER=gzip queue /tmp/artifacts/nodes/$i/messages.gz oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/messages
             oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/journal | sed -e 's|.*href="\(.*\)".*|\1|;t;d' > /tmp/journals
             while IFS= read -r j; do
-              oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/journal/${j}system.journal | gzip -c > /tmp/artifacts/nodes/$i/journal.gz
+              FILTER=gzip queue /tmp/artifacts/nodes/$i/journal.gz oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/journal/${j}system.journal
             done < /tmp/journals
-            oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/metrics | gzip -c > /tmp/artifacts/metrics/node-$i.gz
-            oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/debug/pprof/heap > /tmp/artifacts/nodes/$i/heap
-            oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/secure | gzip -c > /tmp/artifacts/nodes/$i/secure.gz
-            oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/audit | gzip -c > /tmp/artifacts/nodes/$i/audit.gz
-            ) &
+            FILTER=gzip queue /tmp/artifacts/metrics/node-$i.gz oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/metrics
+            queue /tmp/artifacts/nodes/$i/heap oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/debug/pprof/heap
+            FILTER=gzip queue /tmp/artifacts/nodes/$i/secure.gz oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/secure
+            FILTER=gzip queue /tmp/artifacts/nodes/$i/audit.gz oc get --request-timeout=20s --raw /api/v1/nodes/$i/proxy/logs/audit
           done < /tmp/nodes
 
           while IFS= read -r i; do
             file="$( echo "$i" | cut -d ' ' -f 3 | tr -s ' ' '_' )"
-            oc exec $i -- /bin/bash -c 'oc get --raw /debug/pprof/heap --server "https://$( hostname ):8443" --config /etc/origin/master/admin.kubeconfig' > /tmp/artifacts/metrics/${file}-heap
-            oc exec $i -- /bin/bash -c 'oc get --raw /metrics --server "https://$( hostname ):8443" --config /etc/origin/master/admin.kubeconfig' | gzip -c > /tmp/artifacts/metrics/${file}-api.gz
-            oc exec $i -- /bin/bash -c 'oc get --raw /debug/pprof/heap --server "https://$( hostname ):8444" --config /etc/origin/master/admin.kubeconfig' > /tmp/artifacts/metrics/${file}-controllers-heap
-            oc exec $i -- /bin/bash -c 'oc get --raw /metrics --server "https://$( hostname ):8444" --config /etc/origin/master/admin.kubeconfig' | gzip -c > /tmp/artifacts/metrics/${file}-controllers.gz
+            queue /tmp/artifacts/metrics/${file}-heap oc exec $i -- /bin/bash -c 'oc get --raw /debug/pprof/heap --server "https://$( hostname ):8443" --config /etc/origin/master/admin.kubeconfig'
+            FILTER=gzip queue /tmp/artifacts/metrics/${file}-api.gz oc exec $i -- /bin/bash -c 'oc get --raw /metrics --server "https://$( hostname ):8443" --config /etc/origin/master/admin.kubeconfig'
+            queue /tmp/artifacts/metrics/${file}-controllers-heap oc exec $i -- /bin/bash -c 'oc get --raw /debug/pprof/heap --server "https://$( hostname ):8444" --config /etc/origin/master/admin.kubeconfig'
+            FILTER=gzip queue /tmp/artifacts/metrics/${file}-controllers.gz oc exec $i -- /bin/bash -c 'oc get --raw /metrics --server "https://$( hostname ):8444" --config /etc/origin/master/admin.kubeconfig'
           done < /tmp/pods-api
 
           while IFS= read -r i; do
             file="$( echo "$i" | cut -d ' ' -f 2,3,5 | tr -s ' ' '_' )"
-            oc logs --request-timeout=20s $i | gzip -c > /tmp/artifacts/pods/${file}.log.gz
-            oc logs --request-timeout=20s -p $i | gzip -c > /tmp/artifacts/pods/${file}_previous.log.gz
+            FILTER=gzip queue /tmp/artifacts/pods/${file}.log.gz oc logs --request-timeout=20s $i
+            FILTER=gzip queue /tmp/artifacts/pods/${file}_previous.log.gz oc logs --request-timeout=20s -p $i
           done < /tmp/containers
 
-          echo "Waiting for node logs to finish ..."
+          echo "Waiting for logs ..."
           wait
 
           echo "Deprovisioning cluster ..."
-          export AWS_SHARED_CREDENTIALS_FILE=/etc/openshift-installer/.awscred
+          # MODIFIED
+          export AWS_SHARED_CREDENTIALS_FILE=/etc/openshift-installer/credentials
           openshift-install --dir /tmp/artifacts/installer --log-level debug destroy-cluster
         }
 
